### ISSUE TITLE
Cli flag name confusing

### ISSUE THREAD

**Issue by oupala** [ajoslin/conventional-changelog#100]
The module is offering an [append option](https://github.com/ajoslin/conventional-changelog#append).

For reverse CHANGELOGs (blog style), it could be useful to offer a **prepend option**.

**Comment by stevemao** [comment]
The log is either in append or prepend mode (the current behaviour)

**Comment by oupala** [comment]
You mean that prepend mode is the default mode.

Append mode can be choosen by the `-a` option.

Right?

**Comment by stevemao** [comment]
Yeah

**Comment by oupala** [comment]
Ok, I tested it, prepending is possible.

It is however a bit complicated to have this behaviour. As far as I tested, we are obliged to specify the prepended file twice!

```bash
conventional-changelog --preset angular --context changelog.json --infile CHANGELOG.md --outfile CHANGELOG.md --release-count 1
```

**Comment by oupala** [comment]
In fact, the overwrite option allows to prepend the file:

```bash
-w, --overwrite           Overwrite the infile
```

The resulting command line is then:

```bash
conventional-changelog --preset angular --context changelog.json --infile CHANGELOG.md --overwrite CHANGELOG.md --release-count 1
```

But using an **overwrite** parameter for **prepending** is really confusing as it is not overwriting at all.

Maybe the parameter name should be changed as the following:

```bash
-s, --same           Ouputting to the infile in prepending mode
```

In fact, the most confusing thing is that it is the `--release-count` that set if the file will be overwritten or not.

- `--release-count 1` => file prepended
- `--release-count 0` => file overwritten

**Comment by stevemao** [comment]
I agree the flag names might be a bit confusing

**Comment by stevemao** [comment]
Also we should probably remove `--raw-commits-opts`, `--parser-opts` and `--writer-opts` and expose useful options of them with each single flag. `--context` can still be a json file.

**Comment by stevemao** [comment]
@oupala you happy with the cli help message?

https://github.com/stevemao/conventional-changelog-cli/blob/master/cli.js#L13-L46

**Comment by oupala** [comment]
@stevemao Yes, it's good. Except that you kept the spelling mistake I made: change `Ouputting` to `Outputting`.

You also use camelCase sometime while you're using lowercase sometime. For example `sameFile` and `infile` and `outfile` (see https://github.com/stevemao/conventional-changelog-cli/blob/master/cli.js#L50-L52).

**Comment by stevemao** [comment]
Good catch @oupala !

`infile` and `outfile` are kinda convention? but `samefile` looks weird. Thoughts?

**Comment by oupala** [comment]
`samefile` does not look weird to me. But it might be a question of personal feeling.

I don't really mind about this variable name. It was just in case you did not realized you were using difference camelCase styles.

In my opinion, using camelCase and lowercase looks weird to me. But is is not that important.

**Comment by stevemao** [comment]
Will probably keep them like this for now as I can find reference of `infile` and `outfile`. But other values are camelCased

https://github.com/substack/node-browserify#usage

**Comment by oupala** [comment]
If you have a look at *advanced Options* from https://github.com/substack/node-browserify#usage, we mayeb should use `--same-file` instead of `--sameFile`.

It would be more consistent.

**Comment by stevemao** [comment]
It is `--same-file`

**Comment by stevemao** [comment]
It converts to camelCased property.

**Comment by oupala** [comment]
Ok then, it's good.
