### ISSUE TITLE
use full hash

### ISSUE THREAD

**Issue by oupala** [ajoslin/conventional-changelog#102]
I'm using conventional-changelog to write a changelog in markdown.

I'm also using wrtier-opts to change the generated url for each commit. My forge is using the full hash in the url to reference each commit.

I managed to alter the url, but I really need the full hash to generate the url.

Note that I would still need the truncated hash (7 chars) so that the visible label of the link is not too long, but the full hash would be used in the url.

Here is an example of a generated url:

```
* feat(): add changelog page ([d11e82b](https://www.myforge.org/plugins/git/owner/project?p=project.git&a=commit&h=d11e82b))
```

that make the following template (see `shortHash` and `fullHash`):

```
* feat(): add changelog page ([<shortHash>](https://www.myforge.org/plugins/git/owner/project?p=project.git&a=commit&h=<fullHash>))
```

Is it possible to achieve this need?

**Comment by stevemao** [comment]
change https://github.com/ajoslin/conventional-changelog/blob/master/presets/angular.js#L40-L42 in your own settings.

**Comment by oupala** [comment]
Thanks @stevemao for pointing me the right file to change the hash computation.

In order to achieve what I needed, I had to change this file https://github.com/ajoslin/conventional-changelog/blob/master/presets/angular.js#L40-L42 the following way:

```js
      if (typeof commit.hash === 'string') {
        commit.shortHash = commit.hash.substring(0, 7);
      }
```

It is still possible to use the old (long) hash value, but I can also use the new shortHash.

My problem is that I don't see any easy way to add a **preset file** as a parameter of the command line. Hence I had to modify the original file from the original `conventional-changelog` which is installed globally on my workstation. This is not easily portable into continuous integration.

Three questions:

- Do you think this change can be added to the original Angular preset file? (and other preset as well?)
- Or can we imagine to pass a preset file as a parameter of the command line?
- In the end, hash lenght is more tightly linked to presentation (the writer) than to the preset. Would it be a better place to move the hash computation later in the process? Maybe somewhere in the writer opts?

**Comment by stevemao** [comment]
Unfortunately you have do something like this
```
conventional-changelog -p angular -i CHANGELOG.md -w --writer-opts your-writer-opts-file.js
```

**Comment by stevemao** [comment]
> It is still possible to use the old (long) hash value, but I can also use the new shortHash.
```js
if (typeof commit.hash === 'string') {
    commit.shortHash = commit.hash.substring(0, 7);
}
```
Then change your template?

**Comment by stevemao** [comment]
> Do you think this change can be added to the original Angular preset file? (and other preset as well?)

I don't think a long hash would be a common use-case

> In the end, hash lenght is more tightly linked to presentation (the writer) than to the preset. Would it be a better place to move the hash computation later in the process? Maybe somewhere in the writer opts?

This is in the writer options.

**Comment by oupala** [comment]
I'm already using a `personal-writer-opts-file.js` but I don't see the way to specify a custom preset in the documentation of [stevemao/conventional-changelog-writer](https://github.com/stevemao/conventional-changelog-writer).

And, *yes*, I changed the writer template in order to use `hash` and `shortHash` at the right places (the first for linking and the second one for displaying).

**Comment by stevemao** [comment]
You can't define a custom preset... I wonder how the API would look like. Maybe something similar to what eslint does.

**Comment by oupala** [comment]
As far as I understand, it is not possible to use conventional-changelog with a custom forge as conventional-changelog is not as easily customizable as older versions.

If I can't define a custom preset, there is no way to use the original long commit hash, is it?

This is a bad news as this was easily done with a simple js function with older versions of conventional-changelog.

My forge is using the full hash in its commit's url, I supposed that conventional-changelog would be adaptable enough to work with these constraints.

The alternative is to make `hash` and `shortHash` available by default in all presets. Even if it not a common usecase in your opinion, it is a real usecase.

**Comment by stevemao** [comment]
> As far as I understand, it is not possible to use conventional-changelog with a custom forge as conventional-changelog is not as easily customizable as older versions.

True but in the older versions you can't even configure these (I can't remember what could or couldn't be configed but with the older versions you really can't do too much, hence the config is harder now).

> If I can't define a custom preset, there is no way to use the original long commit hash, is it?

It's possible. config `writerOpts` to do this.

The only problem is it's hard to config it. But with the customisable parser and handlebars templates you can do anything.

**Comment by oupala** [comment]
Ok, it is possible but hard to configure. I'll try.

As I said [earlier](https://github.com/ajoslin/conventional-changelog/issues/102#issuecomment-138834166), I don't understand how to configure the `writerOpts`.

Can you give me some tips about how to do this?

**Comment by stevemao** [comment]
Just export an options object in the js file.
```js
module.exports = {
  // options
  groupBy: 'type',
  commitGroupsSort: 'title'
}
```
I think exposing an preset (I believe a better name is config) option would make it "easy" because 
1. combine three files into one.
2. easier to publish to npm.
However, you'll still need to write the same amount of code (hence it's not easier). That's why I just simply did this way.

**Comment by oupala** [comment]
I'm sorry but I don't really understand your last answer.

It is possible to use the original commit hash or not?

If yes, how ? (I searched for it in `writer.opts` but I couldn't find how)
If no, were you talking about creating a new option?

**Comment by stevemao** [comment]
`commit.hash` already exists by default. You just attach another field (`shortHash`) to the `commit` object.

**Comment by oupala** [comment]
Hello @stevemao 

I have two questions:

- how can I attach another field to the `commit` object?
- if `commit.hash` is already the truncated version of the full hash, how can I get bach the full hash? (creating a `shortHash` from `commit.hash` won't help me getting back the full hash in `commit.hash`)

Thanks for your answer.

**Comment by stevemao** [comment]
I already answered your question in the previous comment.
```js
module.exports = {
    transform: function(commit) {
      if (commit.type === 'feat') {
        commit.type = 'Features';
      } else if (commit.type === 'fix') {
        commit.type = 'Bug Fixes';
      } else if (commit.type === 'perf') {
        commit.type = 'Performance Improvements';
      } else if (commit.type === 'revert') {
        commit.type = 'Reverts';
      } else {
        return;
      }

      if (commit.scope === '*') {
        commit.scope = '';
      }

      if (typeof commit.hash === 'string') {
        commit.shortHash = commit.hash.substring(0, 7);
      }

      if (typeof commit.subject === 'string') {
        commit.subject = commit.subject.substring(0, 80);
      }

      _.map(commit.notes, function(note) {
        if (note.title === 'BREAKING CHANGE') {
          note.title = 'BREAKING CHANGES';
        }

        return note;
      });

      return commit;
    }
}
```
`commit.shortHash` will be the short hash and `commit.hash` will be the full hash

**Comment by oupala** [comment]
Thank you @stevemao for the module.

But I still don't understand how to link it with my `conventional-changelog`.

Here is my command line:

```bash
conventional-changelog --preset angular --context changelog/changelog.json --writer-opts changelog/writer.json --infile src/content/pages/changelog.md --overwrite --release-count 1
```

Do I have to add `--parser-opts changelog/parser.json` where `parser.json` is the module that you wrote in the previous comment?

I don't see any way to add a module or a config file as a parameter of the command line:

```bash
>conventional-changelog --help

  Generate a changelog from git metadata

  Usage
    conventional-changelog

  Example
    conventional-changelog -i CHANGELOG.md --overwrite

  Options
    -i, --infile              Read the CHANGELOG from this file
    -o, --outfile             Write the CHANGELOG to this file. If unspecified, it prints to stdout
    -w, --overwrite           Overwrite the infile
    -p, --preset              Name of the preset you want to use
    -k, --pkg                 A filepath of where your package.json is located
    -a, --append              Should the generated block be appended
    -r, --release-count       How many releases to be generated from the latest
    -v, --verbose             Verbose output
    -c, --context             A filepath of a javascript that is used to define template variables
    --git-raw-commits-opts    A filepath of a javascript that is used to define git-raw-commits options
    --parser-opts             A filepath of a javascript that is used to define conventional-commits-parser options
    --writer-opts             A filepath of a javascript that is used to define conventional-changelog-writer options
```

Thanks again in advance for your help.

**Comment by stevemao** [comment]
`--writer-opts` can be either json or js. but in this case its js

**Comment by stevemao** [comment]
BTW, the docs should be enough to answer all your questions. Please send a PR if the docs is not clear.

**Comment by oupala** [comment]
@stevemao I usually do not hesitate to propose a pull request for improving document. I already did this with #92

But I need to understand how it works in order to be able to explain it better, which I'm not sur being able to do this right now.

As soon as I understand the way conventional-changelog works, I will be able to propose a pull request.

**Comment by oupala** [comment]
I'm currently using the following command line in order to generate my changelog:

```bash
conventional-changelog --preset angular --context changelog/changelog.json --writer-opts changelog/writer.json --infile src/content/pages/changelog.md --overwrite --release-count 1
```

where `writer.json` is a json file describing the `commitPartial` template to generate good links.

Two comments above, you advise me to add a `--writer-opts` with a js file in order to modify the hash to keep the long hash in addition to the short hash.

How is it possible to pass a json file **and** a js file as a parameter for `--writer-opts`?

**Comment by stevemao** [comment]
You just pass a js file. I said it can be either a json or js file.

**Comment by oupala** [comment]
Ok, I understand now what you mean. I do not need to pass a js file **and** a json file. I just have to convert the json statements to js statement en mix them in the js file.

I now have an almost working configuration.

Here is my command line:

```bash
conventional-changelog --preset angular --context changelog/changelog.json --writer-opts changelog/writer.js --infile src/content/pages/changelog.md --overwrite --release-count 1
```

Here is my changelog.json:

```json
{
    "host": "https://on.premise.org/forge",
    "repository": "specific-repository-url/?with-parameters",
    "commit": "commit&h",
    "linkCompare": false
}

And finally, my writer.js file:

```js
module.exports = {
    transform: function(commit) {
      if (commit.type === 'feat') {
        commit.type = 'Features';
      } else if (commit.type === 'fix') {
        commit.type = 'Bug Fixes';
      } else if (commit.type === 'perf') {
        commit.type = 'Performance Improvements';
      } else if (commit.type === 'revert') {
        commit.type = 'Reverts';
      } else {
        return;
      }

      if (commit.scope === '*') {
        commit.scope = '';
      }

      if (typeof commit.hash === 'string') {
        commit.shortHash = commit.hash.substring(0, 7);
      }

      if (typeof commit.subject === 'string') {
        commit.subject = commit.subject.substring(0, 80);
      }

      _.map(commit.notes, function(note) {
        if (note.title === 'BREAKING CHANGE') {
          note.title = 'BREAKING CHANGES';
        }

        return note;
      });

      return commit;
    },
    commitPartial: "*{{#if scope}} **{{scope}}:**{{/if}} {{#if subject}}{{subject}}{{else}}{{header}}{{/if}}{{~!-- commit hash --}} {{#if @root.linkReferences}}([{{shortHash}}]({{#if @root.host}}{{@root.host}}/{{/if}}{{#if @root.owner}}{{@root.owner}}/{{/if}}{{@root.repository}}/{{@root.commit}}/{{hash}})){{else}}{{hash~}}{{/if}}{{~!-- commit references --}}{{#if references}}, closes{{~#each references}} {{#if @root.linkReferences}}[{{#if this.owner}}{{this.owner}}/{{/if}}{{this.repository}}#{{this.issue}}]({{#if @root.host}}{{@root.host}}/{{/if}}{{#if this.repository}}{{#if this.owner}}{{this.owner}}/{{/if}}{{this.repository}}{{else}}{{#if @root.owner}}{{@root.owner}}/{{/if}}{{@root.repository}}{{/if}}/{{@root.issue}}/{{this.issue}}){{else}}{{#if this.owner}}{{this.owner}}/{{/if}}{{this.repository}}#{{this.issue}}{{/if}}{{/each}}{{/if}}\n"
};
```

This leads me to an error on execution:

```bash
>conventional-changelog --preset angular --context changelog/changelog.json --writer-opts changelog/writer.js --infile src/content/pages/changelog.md --overwrite --release-count 1
ReferenceError: Error in conventional-changelog-writer: _ is not defined
```

Any idea about why I get this error about "_ undefined"? I suppose the undefined **_** is the one from my writer.js file.

**Comment by stevemao** [comment]
```js
_.map(commit.notes, function(note) {
        if (note.title === 'BREAKING CHANGE') {
          note.title = 'BREAKING CHANGES';
        }

        return note;
      });
```
your `_` is undefined
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined

**Comment by oupala** [comment]
Yeah, I know that my `_` is undefined. But I don't know why.

In fact, I don't know what does this `_` refers to.

I just copied and pasted the code from one of your [previous comment](https://github.com/ajoslin/conventional-changelog/issues/102#issuecomment-139518947).

**Comment by oupala** [comment]
Ok, I added the following line at the beginning of my file:

```js
var _ = require('lodash');
```

And it seems to work.

**Comment by huguangju** [comment]
+1. I need `fullHash` also in my gitlab server, because use `shortHash` can't access the commits url.

**Comment by LanNobul** [comment]
Here is the sample code, we want to customize the changelog file.
The documentation about how to define transform is not clear, it took us a long time to figure it out.

```
const conventionalChangelogCore = require('conventional-changelog-core');
const join = require('path').join;
const readFileSync = require('fs').readFileSync;

const transform = (commit) => {
  let header = '';
  let shortHash = '';

  if(commit.header) {
    header = commit.header.substring(0, 100);
  }

  if(commit.hash) {
    shortHash = commit.hash.substring(0, 7);
  }

  return {...commit, header, shortHash};
};

const writerOpts = {
  groupBy: 'scope',
  commitGroupsSort: 'title',
  commitsSort: ['type', 'subject'],
  noteGroupsSort: 'title',
  mainTemplate: readFileSync(join(__dirname, 'templates/template.hbs'), 'utf-8'),
  headerPartial: readFileSync(join(__dirname, 'templates/header.hbs'), 'utf-8'),
  commitPartial: readFileSync(join(__dirname, 'templates/commit.hbs'), 'utf-8'),
  transform: transform
};

conventionalChangelogCore(options = {}, context = {}, gitRawCommitsOpts = {}, parserOpts = {}, writerOpts)
  .pipe(process.stdout);
```

**Comment by mrt181** [comment]
If you are not using any preset it defaults to `conventional-changelog-writer`.

This one does not have any `writer-opts.js`.

The easiest way for me to get a full hash in this case was to change this line in the [commit.hbs template](https://github.com/conventional-changelog/conventional-changelog/blob/840d139c40a2c4e773794d794c34bc4dbfde27c2/packages/conventional-changelog-writer/templates/commit.hbs#L16)

```diff
-  {{~@root.commit}}/{{hash}}))
+  {{~@root.commit}}/{{raw.hash}}))
```

This uses the full hash in the link and the short hash in the link preview
