### ISSUE TITLE
[conventions/angular] Make `:` after `BREAKING CHANGE` optional

### ISSUE THREAD

**Issue by gr2m** [ajoslin/conventional-changelog#103]
Hey, 

I've already run into this several times. I usually do breaking change commits like [this](https://github.com/eHealthAfrica/kazana-server/commit/f0543c3c6de472161136451bc161d55949f43acc) 

```
BREAKING CHANGE

Before

var Server = require('kazana-server')

    var kazana = new Server('path/to/kazana-app-or-plugin')
    kazana.start(function () {
      console.log('Server running at %s', kazana.info.uri)
    })

Now

    var startKazanaServer = require('kazana-server')

    startKazanaServer('path/to/kazana-app-or-plugin', /*options ,*/ function (error, server) {
      if (error) {
        throw error
      }
      console.log('Server running at %s', kazana.info.uri)
    })
```

I tend to forget the `:` because I do line breaks instead. Any chance we could make the `:` optional?

This is causing quite some headaches for me, because I use [semantic-release](https://github.com/semantic-release/semantic-release) everywhere, and end up with minor releases, but with breaking changes :(

I'm happy to send a PR for that, just point me to the right things on how to do it. 

Thanks :bouquet:

**Comment by jo** [comment]
+1 same here

**Comment by stevemao** [comment]
According to angular's commit guide the : is not optional. If you think it's not reasonable you should probably open an issue there.

**Comment by gr2m** [comment]
@stevemao thanks! Could you please point me to a place I shall create the issue? I don't know which repository that is

**Comment by stevemao** [comment]
both https://github.com/angular/angular and https://github.com/angular/angular.js
ping me when they decide to take your advice.

**Comment by stevemao** [comment]
You can, however, supply your customised `parserOpts` to achieve this :)
