### ISSUE TITLE
Changelog for a release without fixes / features is empty 

### ISSUE THREAD

**Issue by pkozlowski-opensource** [ajoslin/conventional-changelog#11]
Arguably no release should take place where there are no functional changes from the user point of view (`feat`, `fix`) but it might happen that such a release is done nevertheless... In such a case a generated log looks a bit bizarre, here is an example:
https://github.com/karma-runner/karma/blob/master/CHANGELOG.md#v0126-2014-04-09

Maybe adding a small comment, sth like:
 > _There are no functional changes in this release, only documentation updates, refactorings, [list type of changes here] _

@ajoslin WDYT?

**Comment by stevemao** [comment]
Checkout the master branch and see what you can config. With the new apis you can do a lot of crazy things.
At the end of the world if there is nothing in a release I don't think we can do anything about it. You should probably manually write the changelog or try other config.
