### ISSUE TITLE
Support bower.json as alternative to package.json

### ISSUE THREAD

**Issue by huerlisi** [ajoslin/conventional-changelog#110]
bower.json has a similar structure as package.json has. It seems to support all the fields conventional-changelog uses (version, repository...). I've successfully passed `k bower.json`.

I think it would be sensible to allow `bower.json` as a fallback default for `package.json` for the `pkg` parameter.

**Comment by stevemao** [comment]
The `version` in `bower.json` is moot and a lot of people removed it. I don't think it is as valuable. As a lot of people are using `npm` for their client side development, I don't believe people would only have `bower.json` but no `package.json`. Closing now unless there is a real need.

**Comment by klarkc** [comment]
For frontend-only packages this feature is really valuable. I could use this a lot in Polymer web-components (in fact I am already using, but with some manual tasks).
