### ISSUE TITLE
no docs on how to use `transform`

### ISSUE THREAD

**Issue by seiyria** [ajoslin/conventional-changelog#113]
It's pretty frustrating to try to figure this out.

I've tried this:
```js
gulp.task('generate:changelog', function() {
  return changelog({
    releaseCount: 0,
    transform: function(commit, cb) {
      console.log(commit, cb);
      return cb(null, commit);
      // if(_.contains(commit.header, ['bump'])) return false;
    }
  })
    .pipe(fs.createWriteStream('CHANGELOG.md'));
});
```

I've also tried passing in `{ transform: ()... }` as the last param (`writerOpts`). I've tried returning true, returning false, returning callback(). All I'm trying to do is filter out some bad commits from my changelog.

[edit]
Some mild success doing it this way: 
```js
transform: function(commit, cb) {
      console.log(commit);
      if(_.contains(commit.header, ['bump'])) return cb(null);
      return cb(null, commit);
    }
```

and having it on the first options object. This merges everything into the latest tag though which is ... not desirable.

**Comment by stevemao** [comment]
I think you need `writerOpts.transform`. PR welcome to improve the naming confusing :)

Idealy
> // it would be better to if `gitRawCommits` could spit out better formatted data
        // so we don't need to transform here

**Comment by stevemao** [comment]
Or suggest better names.

**Comment by seiyria** [comment]
Yeah, I'm not entirely sure. I couldn't even give a PR because I have no idea how to make it work as expected. That said, I just rebased my whole repo and started using the angular convention, so this isn't that big of a deal anymore.

Still, having some documentation on how to use `transform` would be a good idea.

**Comment by stevemao** [comment]
First thing first, if someone could suggest better API names (there are three `transform`s) it would be great.

**Comment by stalinkay** [comment]
Hi @stevemao Is it possible to use a custom clone of the angular preset with the CLI. I can get it to work by dropping it into the global conventional-changelog directory and simply specifying the name of my custom preset.

**Comment by stevemao** [comment]
Use `--config`

**Comment by stevemao** [comment]
Could you look into it and see what the problem is? If there's any bug please open a new issue. Thanks!

**Comment by stalinkay** [comment]
@stevemao Ok. Cool.
