### ISSUE TITLE
Generate full change log

### ISSUE THREAD

**Issue by davinkevin** [ajoslin/conventional-changelog#117]
Hi, 

As an new user of the 0.5.X version (and old user of 0.0.11), I would like to generate a full changelog of my project (which uses conventional changelog commit style, but don't generate changelog.md).

I don't find the help in the doc to do that... or I have a problem...
When I do ```conventional-changelog -p angular -i CHANGELOG.md -w -r 0``` (or same thing with gulp helper), I have a changelog with only the few commits... (not all).

And if I do the ```conventional-changelog -p angular -i CHANGELOG.md -w``` another times it prepends the same thing (list of commit and title..).

In the past (with 0.0.11), we used to specify the from / to commit hash to generate the changelog and append it to the changelog. Could we reproduce this behavior with the new version ? 

```js
gulp.task('conventional-changelog', function(done){
  function changeParsed(err, log){
    if (err) {
      return done(err);
    }
    fs.writeFile('CHANGELOG.md', log);
  }
  fs.readFile('./package.json', 'utf8', function(err, data){
    var ref$, repository, version;
    ref$ = JSON.parse(data), repository = ref$.repository, version = args.vname || ref$.version;
    conventionalchangelog({
      repository: repository.url,
      version: version,
      from: from,
      to: to
    }, changeParsed);
  });
}
```

A link to the project I'm talking to : https://github.com/davinkevin/angularjs-jspm-seed

**Comment by stevemao** [comment]
```
$ conventional-changelog -p angular -i CHANGELOG.md -w -r 0
```
should generate all changelog. https://github.com/ajoslin/conventional-changelog/blob/master/test/test.js#L309-L331 is the prove

**Comment by davinkevin** [comment]
After some investigation, it seems I didn't respect the template and I don't understand very well the workflow (with the tag release). I worked with @aubm to find out the solution... and all the task to be done have been added to a gulp task (https://github.com/davinkevin/angularjs-jspm-seed/blob/master/build/tasks/conventional-changelog.js)

Thanks for your answer
