### ISSUE TITLE
Recommended Commit-Message Validator?

### ISSUE THREAD

**Issue by gamename** [ajoslin/conventional-changelog#118]
Hi,

Conventional-Changelog is great.  But the problem for us is making sure we conform to the standard in our commit messages.  Is there any particular script which you guys recommend for using as a git hook for CC commit message validation? 

TIA

**Comment by stevemao** [comment]
jQuery is using [commitplease](https://github.com/jzaefferer/commitplease), angular.js is using [this script](https://github.com/angular/angular.js/blob/master/validate-commit-msg.js). There are many other git hook modules.

**Comment by stevemao** [comment]
You might also wanna try [commitizen](https://github.com/commitizen/cz-cli) - Simple commit conventions for internet citizens.

**Comment by gamename** [comment]
Thanks!
