### ISSUE TITLE
Possible to create changelog from start of a project?

### ISSUE THREAD

**Issue by JamieMason** [ajoslin/conventional-changelog#119]
Apologies if this is documented somewhere, but I've been unable to find it.

Is it possible to run `conventional-changelog` so that it generates a complete changelog from the beginning of your git log, rather than just append an entry for the most recent tag? I have a repo that follows the angular convention for git commit messages, but am only now integrating `conventional-changelog`.

Thanks for your time.

Jamie, [@fold_left](https://twitter.com/fold_left)

**Comment by stevemao** [comment]
> If you first time use this tool and want to generate all previous changelog, you could do
```
$ conventional-changelog -p angular -i CHANGELOG.md -w -r 0
```

This is written in the beginning of the doc

**Comment by JamieMason** [comment]
Looks like I need more Coffee @stevemao, sorry about that.

**Comment by stevemao** [comment]
No worries @JamieMason :)

**Comment by sebastienbarre** [comment]
Apologies, but I can't quite figure it out either.
```
(master)$ conventional-changelog -p angular -r 0
TypeError: Cannot read property 'version' of undefined
```
I should add that this is not a node/npm/Javascript repo, there is no `package.json` here. Nevertheless, I'd like to use Angular's commit log conventions for all my projects and generate a weekly changelog, say, for the work that was done in the past 7 days. Maybe by passing it a date, or a reference to a commit SHA1, so that it would generate a log based on all the changes since that date/commit.

Thanks

**Comment by stevemao** [comment]
What version are you using?

**Comment by sebastienbarre** [comment]
```
├── commitizen@2.4.6
├── conventional-changelog@0.5.1
├── cz-conventional-changelog@1.1.4
```

**Comment by stevemao** [comment]
Please always use the latest version before you post any issue :)

**Comment by sebastienbarre** [comment]
It's a good thing that I am already, then :)

**Comment by stevemao** [comment]
Sorry. I think it might be a problem with no package.json. I can't test it now but looks like a potential issue. Can you create another issue for me to track?

**Comment by sebastienbarre** [comment]
Of course. See #123

**Comment by stevemao** [comment]
Thanks
