### ISSUE TITLE
Expose the `grep` option, add "Other fixes" section

### ISSUE THREAD

**Issue by vladikoff** [ajoslin/conventional-changelog#12]
How about exposing the `grep`([ref](https://github.com/ajoslin/conventional-changelog/blob/master/lib/git.js#L41)) option, this way you can set which conventions you want in the changelog. The additional commits with conventions that don't match Fix, Feature, Breaking would be grouped as  "Other fixes" in the changelog. 

Thoughts?

**Comment by stevemao** [comment]
Please checkout the rewrite on the master branch and see if the problem still exists. Thanks.
