### ISSUE TITLE
Consider an "Unreleased" section

### ISSUE THREAD

**Issue by seriema** [ajoslin/conventional-changelog#120]
I liked this idea from http://keepachangelog.com:

> Always have an `"Unreleased"` section at the top for keeping track of any changes.

> This serves two purposes:

> * People can see what changes they might expect in upcoming releases
> * At release time, you just have to change `"Unreleased"` to the version number and add a new `"Unreleased"` header at the top.

Currently if I run `conventional-changelog` (technically `grunt-conventional-changelog` version `5.0.0`) without a new git tag I get the latest release number repeated. Maybe the fallback if there's no tag could be "Unreleased" instead?

Example output from my project, note the repeated `0.3.2`:

````
<a name="0.3.2"></a>
## [0.3.2](https://github.com/seriema/angular-apimock/compare/0.3.2...v0.3.2) (2015-10-27)


### Bug Fixes

* **npm:** `npm install` was failing because it ran bower as `postinstall` ([a696e14](https://github.com/seriema/angular-apimock/commit/a696e14))



<a name="0.3.2"></a>
## [0.3.2](https://github.com/seriema/angular-apimock/compare/0.3.1...v0.3.2) (2015-10-25)
````

**Comment by stevemao** [comment]
I like the idea! But the module doesn't know if `0.3.2` has released or not. 

Currently I can think of two ways of doing it
1. always change your version in package.json to something else (eg: '0.3.3-pre' or 'Unreleased' in your case) before you do a release.
2. manually give a version when you run the command.

The limitation of this module is it only generate changelog, but it doesn't read any previous generated changelog.

**Comment by seriema** [comment]
I'm guessing it reads the latest tag, to generate the header, and then somehow works out what commits to use for the changelog. How does it do that?

The generated sample above shows it's creating links to github:
`https://github.com/seriema/angular-apimock/compare/0.3.2...v0.3.2`
`https://github.com/seriema/angular-apimock/compare/0.3.1...v0.3.2`
The last part of those URL's are interesting: `0.3.2...v0.3.2` and `0.3.1...v0.3.2`.  A naive idea would be "if they are the same, then set the version name to `Unreleased`".

Or basically any commits after the latest tag would work, but the changelog are picking them up now anyway so I'm not sure how it's calculating the diff.

**Comment by stevemao** [comment]
> if they are the same, then set the version name to Unreleased

hm... Maybe just don't generate it. Some people have problem with the [workflow](https://github.com/stevemao/conventional-changelog-cli#recommended-workflow) here so this might solve that problem.

**Comment by stevemao** [comment]
You might see something like this with "Unreleased"

```md
<a name="0.3.2"></a>
## [0.3.2](https://github.com/seriema/angular-apimock/compare/0.3.1...v0.3.2) (2015-10-27)


### Bug Fixes

* **npm:** `npm install` was failing because it ran bower as `postinstall` ([a696e14](https://github.com/seriema/angular-apimock/commit/a696e14))




## Unreleased


### Bug Fixes

* **npm:** `npm install` was failing because it ran bower as `postinstall` ([a696e14](https://github.com/seriema/angular-apimock/commit/a696e14))
```

The entry will appear again in the next release section. Thoughts?

**Comment by seriema** [comment]
Maybe it can be an option to include it or not?

Not sure what you mean with the example above. Why would I see my commit twice? It's not doing that now. It's generating the list correctly, it's just the header that's wrong.

**Comment by stevemao** [comment]
> if they are the same, then set the version name to Unreleased

So once you tag it with a different semver number, you would prepend the change log with the new release.

**Comment by seriema** [comment]
Oh, of course! Yeah maybe it's best to just not output it.
