### ISSUE TITLE
[Question] How to use the writer-opts?

### ISSUE THREAD

**Issue by angelblade27** [ajoslin/conventional-changelog#124]
I'm trying out using conventional-changelog with the  --writer-opts however I can't get the host url to change for my commits. I'm running like so
conventional-changelog -p angular -r 1  --writer-opts ./src/conf/conventional-changelog-writer.js

Where conventional-changelog-writer.js is
```javascript
module.exports = {

    host : "https://github.com"

};
```

The output i'm getting is
```bash
<a name="0.2.51"></a>
## [0.2.51](/http://1022/test/compare/v0.2.51...v0.2.51) (2015-11-28)


### Bug Fixes

* boo ([5981e03](http://1022/test/commits/5981e03))

### Features

* **package.json:** Hey look at me ([14b8548](http://1022/test/commits/14b8548))
```

as you can see the links to the commits are going to 'http://1022/'

**Comment by stevemao** [comment]
`host` option should be under `context` https://github.com/stevemao/conventional-changelog-writer#host

**Comment by angelblade27** [comment]
So doing 
```javascript
module.exports = {
	context: {
		host: "https://github.com"
	}
};
``` 
still yields the same results

**Comment by stevemao** [comment]
I will change the cli flags. for now, use https://github.com/ajoslin/conventional-changelog/blob/master/cli.js#L28

**Comment by angelblade27** [comment]
@stevemao 
Cool that kind of works I did
```bash
conventional-changelog -p angular -r 1 --context ./src/conf/conventional-changelog-writer.js
```

With the conventional-changelog-writer.js as 
```javascript
module.exports = {

    host : "https://github.com"

};
```

And it added the url however it didn't replace the "http://1022" part of it
```markdown
<a name="0.2.51"></a>
## [0.2.51](https://github.com/http://1022/test/compare/v0.2.51...v0.2.51) (2015-11-28)


### Bug Fixes

* boo ([5981e03](https://github.com/http://1022/test/commits/5981e03))

### Features

* **package.json:** Hey look at me ([14b8548](https://github.com/http://1022/test/commits/14b8548))
```

**Comment by stevemao** [comment]
where is `'http://1022/'` from?

**Comment by angelblade27** [comment]
from the package.json ( removed our internal host we have it on)  it looks like
```javascript
 "repository": {
    "type": "git",
    "url": "ssh://<internal host>:10022/test.git"
  },
```

**Comment by angelblade27** [comment]
So it looks like adding repository will overwrite the whole thing correctly however ideally I would like it scrap the repository from the package.json as I was going to have other packages pull this custom grunt task so that it works out of the box.

```javascript
module.exports = {

		host: 'https://github.com',
        repository: 'angelblade27'
};
```

```javascript
<a name="0.2.51"></a>
## [0.2.51](https://github.com/angelblade27/compare/v0.2.51...v0.2.51) (2015-11-28)


### Bug Fixes

* boo ([5981e03](https://github.com/angelblade27/commits/5981e03))

### Features

* **package.json:** Hey look at me ([14b8548](https://github.com/angelblade27/commits/14b8548))
```

**Comment by stevemao** [comment]
> ideally I would like it scrap the repository from the package.json

repository defaults to the parsed result from the repo url in package.json. You can overwrite the default. Does that answer your question?

**Comment by angelblade27** [comment]
Kind of. 
So if the url is 
ssh://localhost:1022/test.git why does it still append http://1022 when I only have 'host' set?
Shouldn't it just automatically pull 'test' as the repository and not have 'http' + port number along with the ? 
Instead of hardcoding the repository name can I override it with a regex to parse the repository url correctly?

**Comment by stevemao** [comment]
> Shouldn't it just automatically pull 'test' as the repository and not have 'http' + port number along with the ? 

Can you check if getPkgRepo module can parse your url correctly and the `context` object (https://github.com/ajoslin/conventional-changelog/blob/master/index.js#L126) contains the right data
'

> Instead of hardcoding the repository name can I override it with a regex to parse the repository url correctly?

Not really.

**Comment by stevemao** [comment]
@angelblade27 any news?

**Comment by angelblade27** [comment]
Sorry was sick and then forgot to get to this. 
Is that what you mean I dumped some of those parameters by doing
```
           context.owner = context.owner || repo.user || '';
            context.repository = context.repository || repo.project || browse;
            console.log('repository:' + context.repository);
            console.log('repo.project:' + repo.project);
            console.log('browse:' + browse);
```
Output was
```
repository:<our project>/test
repo.project:undefined
browse:http://10022/test

**Comment by stevemao** [comment]
Can you use the same settings that you can produce https://github.com/http://1022/test/commits/5981e03?

**Comment by angelblade27** [comment]
Ok removed the repository.  Just to clarify the command is 
`node node_modules/conventional-changelog/cli.js -p angular -r 1 --context ./src/conf/conventional-changelog-writer.js`. I wrote a grunt target to execute this.
The conventional-changelog-writer.js has 
```
module.exports = {
	//Override the host url that gets scraped from the package.json to link to our git lab
	host: 'https://gitlab-app.eng.qops.net',
	//When overriding the host we need to override the repository as well.
	//repository: 'testcore'
};
```
package.json url is
```
  "repository": {
    "type": "git",
    "url": "ssh://<internal host>:10022/testcore.git"
  },
```
output is
```
repository:http://10022/testcore
repo.project:undefined
browse:http://10022/testcore
```

**Comment by stevemao** [comment]
It looks like getPkgRepo module cannot understand your repo url.

**Comment by angelblade27** [comment]
Is it because we have a port number there?

Sent from my iPhone
~S

**Comment by stevemao** [comment]
Maybe. Also because your host is a customised host so the module doesn't understand it. Can you print the results parsed by getPkgRepo so the problem is clearer? Thanks.

**Comment by angelblade27** [comment]
output of getPkgRepo is
```
{ protocol: '<internal host>:',
  slashes: null,
  auth: null,
  host: '10022',
  port: null,
  hostname: '10022',
  hash: null,
  search: null,
  query: null,
  pathname: '/test.git',
  path: '/test.git',
  href: '<internal host>:10022/test.git',
  browse: [Function] }
```

**Comment by angelblade27** [comment]
I noticed you mention https://github.com/ajoslin/conventional-changelog#transform however I don't see what arg to use to pass this option via commandline also not sure exactly how to use it. It mentions it takes package.json as arg and transforms it but how do you get it transform it. Sorry if it is a stupid question. If there is a code example I can look at that.

**Comment by stevemao** [comment]
https://github.com/ajoslin/conventional-changelog/blob/master/test/test.js#L171-L174

**Comment by stevemao** [comment]
I tried parsing `'ssh://abc:10022/testcore.git'` (I replaced you `<internal host>` with `'abc'`) and it returns me 

```js
Url {
  protocol: 'ssh:',
  slashes: true,
  auth: null,
  host: 'abc:10022',
  port: '10022',
  hostname: 'abc',
  hash: null,
  search: null,
  query: null,
  pathname: '/testcore.git',
  path: '/testcore.git',
  href: 'ssh://abc:10022/testcore.git' }
```

**Comment by angelblade27** [comment]
That is weird which version are you using or is it directly from the code just wondering if that might be?

Sent from my iPhone
~S

**Comment by stevemao** [comment]
I use node4. I briefly tested with getPkgRepo directly. Same as `url.parse`.

**Comment by stevemao** [comment]
Is your problem solved? @angelblade27

**Comment by angelblade27** [comment]
I think it is the node version we are on an very old version
