### ISSUE TITLE
[Question]  Refer to Pull Request Comments like "Fixes:"?

### ISSUE THREAD

**Issue by gamename** [ajoslin/conventional-changelog#125]
Hi,

I don't know if this is the right place to ask, but here goes..

Has there ever been in thought of using links to pull request comments in the footer?  If, for example, someone adds "change foo to bar" in a PR comment, it would be nice to have something like "PRComment  <foo_bar_link>".  Its not a fix per se, but it is a direct action that should have its origin noted somehow.

**Comment by stevemao** [comment]
related https://github.com/ajoslin/conventional-changelog/pull/107

**Comment by stevemao** [comment]
@gamename is it related to #107? Can you provide an example of what you would like to see?

**Comment by stevemao** [comment]
I think I know what you mean. Why do you want to see a link to an issue comment?

**Comment by stevemao** [comment]
If you want links to  pull request comments you can put them into the body of the commit message.
