### ISSUE TITLE
[Question / Potential Feature Request] Collapse similar name and type

### ISSUE THREAD

**Issue by michaelbpaulson** [ajoslin/conventional-changelog#126]
Example commit messages:

```
feat(pencil): Added #2 to the API
feat(pencil): Added HB to the API
feat(pencil): Added the borrow feature
```

This produces the following changelog

-----------------------

### Features

* **changelog:** Another one for the books. ([ba4b108](https://github.com/Netflix/falcor/commit/ba4b108))
* **changelog:** Test2 is where the biggest changes ([30dea4c](https://github.com/Netflix/falcor/commit/30dea4c))
* **changelog:** This is the first change. ([1fb6387](https://github.com/Netflix/falcor/commit/1fb6387))

---------------------------------
It seems like the better option, instead of repeating over and over again would be to collapse. 

Example of what I* think it should look like.

### Features

* **changelog:** 
  * Another one for the books. ([ba4b108](https://github.com/Netflix/falcor/commit/ba4b108))
  * Test2 is where the biggest changes ([30dea4c](https://github.com/Netflix/falcor/commit/30dea4c))
  * This is the first change. ([1fb6387](https://github.com/Netflix/falcor/commit/1fb6387))

Thoughts?  Perhaps this has already been fixed, but I could not find any options in `--help`.
\* Its just an opinion, but this is a desire of the falcor team.

**Comment by stevemao** [comment]
Can you change your templates to achieve this?

**Comment by michaelbpaulson** [comment]
@stevemao could you point me to some docs to accomplish this?

**Comment by stevemao** [comment]
https://github.com/stevemao/conventional-changelog-writer#maintemplate

**Comment by stevemao** [comment]
@michaelbpaulson any updates?

**Comment by michaelbpaulson** [comment]
Sorry, I thought I closed this ticket down.  I am going to try to build a template today or monday.

**Comment by stevemao** [comment]
@michaelbpaulson any luck?

**Comment by michaelbpaulson** [comment]
So sorry! I have been tied up with other tasks for now. I'll circle back
some time in the future.

**Comment by stevemao** [comment]
No worries :)
