### ISSUE TITLE
Take issue tracker url in consideration

### ISSUE THREAD

**Issue by 5im0n** [ajoslin/conventional-changelog#128]
npm allow to add bugs url in the package.json: https://docs.npmjs.com/files/package.json#bugs

```JSON
{
"bugs": {
  "url": "http://issue-tracker/issue/"
}
```

It seems that conventional-changelog don't use this url. Indeed I have a projet with issues tracker base on Redmine. For instance:

* **contact:** add contact page ([c594ae3]()), closes [#952]()

The link commit `c594ae3` use the repository url, sounds goog
The link issue `#952` use also the repository url

**Comment by stevemao** [comment]
It uses [normalize-package-data](https://github.com/npm/normalize-package-data#what-normalization-currently-entails) to normalise data the same way as npm.

**Comment by stevemao** [comment]
Oh i see what you mean, you want to use `bugs.url` to be your issue url.

**Comment by 5im0n** [comment]
Exactly :smiley:

Even if you have `bugs.url` define in your package.json, the changelog is always generated with `repository.url` for issue reference

**Comment by stevemao** [comment]
Makes sense, it also makes it possible for jira.

**Comment by 5im0n** [comment]
Of course.

You have the `get-pkg-repo` module to get the package repository.
I don't think we need to create a `get-pkg-bugs` module to help the `conventional-changelog` to get the issue tracker url.
 
If `bugs.url` is defined we just need to use it.

**Comment by stevemao** [comment]
Should probably fall back to `git remote`

**Comment by stevemao** [comment]
Using bugs url in the package.json should be already possible. the [package.json value is attached to the context](https://github.com/stevemao/conventional-changelog-core#packagedata) and you just need to customise your template.

**Comment by heavenmirror** [comment]
not work for me.
I use conventional-changelog-cli.
config bugs.url

**Comment by stevemao** [comment]
How can I replicate it?

**Comment by heavenmirror** [comment]
I set package.json.
```json
{
  "name": "test-demo",
  "version": "v1.7.2",
  "description": "",
  "main": "index.js",
  "scripts": {
    "changelog": "conventional-changelog -p angular -i CHANGELOG.md -s",
    "changelog-all": "conventional-changelog -p angular -i CHANGELOG.md -s -r 0"
  },
  "repository": {
    "type": "git",
    "url": "http://bitbucket-demo.app/users/test/repos/zhangyi-demo"
  },
  "bugs": {
  	"url": "http://jira-demo.app/browse"
  },
  "author": "",
  "license": "ISC"
}
```
when i excute `conventional-changelog -p angular -i CHANGELOG.md -s`.
closes cann't link to the bugs.url `http://jira-demo.app/browse/9836`

**Comment by batje** [comment]
I am not sure the closing commit solves the required feature. It would be great if 2 links were generated,

and one like this (which already works) [commit](https://github.com/conventional-changelog/conventional-changelog/commit/ff22fe652bac6cc2fd4889669f2159e2df59eae9)

And one like this (which is the new request)  (random example): #120

**Comment by stevemao** [comment]
@batje can you elaborate?

**Comment by batje** [comment]
sure.

It would be great if the changelog looked something like this:

`* Take issue tracker url in consideration in commit ([ff22fe652bac6cc2fd4889669f2159e2df59eae9](https://github.com/conventional-changelog/conventional-changelog/commit/ff22fe652bac6cc2fd4889669f2159e2df59eae9)) closes ([#128](https://github.com/conventional-changelog/conventional-changelog/issues/128))`

Which should render as


* Take issue tracker url in consideration([ff22fe652bac6cc2fd4889669f2159e2df59eae9](https://github.com/conventional-changelog/conventional-changelog/commit/ff22fe652bac6cc2fd4889669f2159e2df59eae9)) closes ([#128](https://github.com/conventional-changelog/conventional-changelog/issues/128))

Where the link to the issue is taken from the package.json 'bugs.url' property + hash128 automagically.

**Comment by felixsteghofer** [comment]
No update here, right?
Would like to help getting this issue resolved.

**Comment by stevemao** [comment]
It doesn't take `bugs.url` now. We are considering it. There are downsides like you can't reference another repo etc.
At the meanwhile you could configure it.

**Comment by nfantone** [comment]
@stevemao Are you guys still "considering" this after two years? The main issue, as far as I understand it, at least, is that if using the `angular` preset the issues URL seems to be [forced by replacing text on the commit subject](https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/conventional-changelog-angular/writer-opts.js#L75). It cannot be handled or modified using a template.
