### ISSUE TITLE
Option for commits patterns

### ISSUE THREAD

**Issue by ocombe** [ajoslin/conventional-changelog#13]
I would like to be able to use a custom commit pattern. It would be nice to have an option to customize the following regex:
```js
var COMMIT_PATTERN = /^(\w*)(\(([\w\$\.\-\* ]*)\))?\: (.*)$/;
```

And also I would like to be able to list more than just `feat` & `fix` commits in the changelog (`docs` for example, and probably other things later), it would be nice to be able to provide a list of the headers to parse.

If you don't have the time to do it but think it's a good idea, just tell me and I'll work on it and send a PR.

**Comment by stevemao** [comment]
Also a custom closes pattern would be nice

https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by ocombe** [comment]
Woot!! \o/
Thanks a lot Steve!

**Comment by stevemao** [comment]
Please checkout the rewrite on the master branch and see if the problem still exists. Thanks.
