### ISSUE TITLE
Fetch version from npm repository instead of package.json

### ISSUE THREAD

**Issue by dbartholomae** [ajoslin/conventional-changelog#134]
Hi there,

I would like to use conventional-changelog in concert with [semantic-release](https://gitter.im/semantic-release/semantic-release). Semantic release updates the version number in the build phase on travis, and therefore doesn't save it to package.json.
It would be great if conventional-changelog could pull the current version from the npm repo instead of package.json to avoid this issue.
Since this might be breaking for some, it should be an optional option.

If you are interested I will take a look and see if I can create a pull request.

Best,
Daniel

**Comment by stevemao** [comment]
You can set the [context](https://github.com/ajoslin/conventional-changelog#context) to achieve this.
