### ISSUE TITLE
Do not change changelog if there is nothing to add

### ISSUE THREAD

**Issue by dbartholomae** [ajoslin/conventional-changelog#135]
Hi there,

currently I'm using converntional-changelog in an automated process. It would be pretty useful if it would not output empty lines with the old version number when there is no change.

If you are interested I would work on a pull request.

Best,
Daniel

**Comment by stevemao** [comment]
What do you mean "it would not output empty lines with the old version number when there is no change"? Can you provide more details?

**Comment by dbartholomae** [comment]
Sure! If my changelog currently is

> <a name="2.1.0"></a>
> # [2.1.0](https://github.com/dbartholomae/ng-q-plus/compare/v2.0.0...v2.1.0) (2016-01-10)
> 
> ### Features
> 
> * **deep:** implement .deep to resolve nested objects and arrays of promises ([4f80a7c (https://github.com/dbartholomae/ng-q-plus/commit/4f80a7c))

then after running conventional-changelog again without any other changes it will become

> <a name="2.1.0"></a>
> # [2.1.0](https://github.com/dbartholomae/ng-q-plus/compare/v2.0.0...v2.1.0) (2016-01-10)
> 
> <a name="2.1.0"></a>
> # [2.1.0](https://github.com/dbartholomae/ng-q-plus/compare/v2.0.0...v2.1.0) (2016-01-10)
> 
> ### Features
> 
> * **deep:** implement .deep to resolve nested objects and arrays of promises ([4f80a7c (https://github.com/dbartholomae/ng-q-plus/commit/4f80a7c))

**Comment by stevemao** [comment]
Have you tried to config writerOpts.generateOn?

**Comment by stevemao** [comment]
Published conventional-changelog-writer 0.4.2 and you can check `commits` in `writerOpts.generateOn`! Thanks for reporting this :smile:

**Comment by dbartholomae** [comment]
Is there a way to use this from CLI? :)

**Comment by stevemao** [comment]
Yeah, `--writer-opts`

**Comment by dbartholomae** [comment]
Could you give me a short example how to invoke `--writer-opts`? I tried `conventional-changelog -p angular -i CHANGELOG.md -w --writer-opts "--generate-on \"commit\""` and got "Failed to get file".

**Comment by stevemao** [comment]
Please use `--help` to find docs. If they are not clear enough, send a PR please :)

**Comment by dbartholomae** [comment]
Thanks! I only looked at the documentation on Github. If you are interested I would create a pull request adding the documentation from --help to the README.md :)

**Comment by stevemao** [comment]
> All available command line parameters can be listed using CLI : conventional-changelog --help.
It was there but I removed it to keep it dry. And we added above instruction.

**Comment by dbartholomae** [comment]
Ok, personally I always prefer it when documentation is available online, too, as it's easier to search online than via console, but that's your choice :)

Based on what I learned from the module I think it makes more sense for me to write an adapter script than use it via CLI. The idea is to make `conventional-changelog` work with `semantic-release` which automatically publishes updated versions to github and npm but unfortunately creates a changelog only via Github Releases and not as a file.
If you're interested, I'll keep you posted on my progress.

**Comment by stevemao** [comment]
There is already a [conventional-github-releaser](https://github.com/stevemao/conventional-github-releaser). I will write more cli docs once some other work is done.

**Comment by dbartholomae** [comment]
Thanks! All I need now is a combination of both ;-)
I'll be working on it :)

**Comment by stevemao** [comment]
Let me know how it goes :)
