### ISSUE TITLE
WIP?

### ISSUE THREAD

**Issue by rafaelrinaldi** [ajoslin/conventional-changelog#136]
What approach should I follow to name work in progress? Imagine that I'm working on a feature but haven't finished it yet but I want to send it to SCM anyway. Should I just use `feat` and specify that's a WIP on the commit message body? Is there a standard for that?

**Comment by stevemao** [comment]
I don't know. I believe this is not related to this tool.

**Comment by stevemao** [comment]
@rafaelrinaldi The angular commit schema is best for perfect commits (with PRs and code reviews I believe). It's probably not the best for temporary commits styles.

I'd suggest you to checkout [standard-version](https://github.com/conventional-changelog/standard-version)
