### ISSUE TITLE
Customising the output: --context, --writerOpts, --parserOpts, and the command line

### ISSUE THREAD

**Issue by xcambar** [ajoslin/conventional-changelog#138]
Hi,
I've been extensively reading the various issues and repos relative to this project and though you indicate clearly that one should be able to customise the transform to output more types than the default ones, and even if the writer documentation states that I can use an object for the `transform` key, I can't even start to think of the beginning of an idea of what my CLI options would look like.

Can you provide an example about how to change the output types with the CLI, please? Or, if not possible, a quick gist on how to do it programmatically, maybe?

On a broader scale, having a thorough example about the possible options would be amazing, but it's a lot more work, admittedly.

Thank you for the project and your help.

**Comment by stevemao** [comment]
Have you read the README of the modules yet? The unreleased code on master has been changed a lot. Especially https://github.com/stevemao/conventional-changelog-cli/blob/master/cli.js#L12-L46

**Comment by xcambar** [comment]
I did and apart from a couple of issues in the repo, there's no clue (or no obvious central piece of information) on the format and contents of the files pointed at by `--context` and `--config`.

**Comment by stevemao** [comment]
`--config` details are [here](https://github.com/stevemao/conventional-changelog-core#config)
`--context` is a json

Please send a PR to improve the description. Thanks.

**Comment by xcambar** [comment]
Call me stupid if you will, but even though I've already read your link before and I know `--context` is a JSON (I discovered that here https://github.com/ajoslin/conventional-changelog/issues/124), I can't find anything remotely helpful. I just don't understand how to use this.

I would be very happy to help with a PR to improve the description, but unfortunately, I don't have the slightest idea of what the interfaces to these options are, _ie_, what keys are accepted in the file pointed by `--context` or how I can use `--config`.

Again, call me stupid, but there is a number of issues related to this issue without a definitive answer.

**Comment by xcambar** [comment]
But again, without being too broad concerning the interfaces, is there a way to select which types of commits get output to the CHANGELOG?

If you would be kind enough to answer this, I would definitively add this to the documentation of the project, if you think it's a good addition.

**Comment by stevemao** [comment]
` -c, --context             A filepath of a json that is used to define template variables'`
It mentions this is a filepath of a json.

>is there a way to select which types of commits get output to the CHANGELOG?

it really depends on what you need. all options should be across the modules.

**Comment by xcambar** [comment]
Closing for lack of actual help. Got it working with `https://github.com/rafinskipg/git-changelog` meanwhile.

**Comment by stevemao** [comment]
How am I not helping you? I answered all your questions. You don't need to go through issues to find out how to use the tool. The readme is supposed to be enough. If not, send a PR to improve it. You only said you want to select which types of commits get output to the CHANGELOG, this is extremely vague, what do you really mean select which type? and all options are already written in the docs.

**Comment by leomYili** [comment]
I succeeded, but took a lot of detours;

"changelog": "conventional-changelog -c ./changelog.context.json ";

and

changelog.context.json
```
{
    "version":"VXXX";
    ....
}
```

**Comment by trallnag** [comment]
@leomYili, could you please elaborate? I'm failing to configure conventional-changelog to do what I want.

Here is my config JSON:

```json
{
    "types": [
        {"type": "feat", "section": "Features", "hidden": true},
        {"type": "fix", "section": "Bug grgrgr"},
        {"type": "perf", "section": "Performance"},
        {"type": "refactor", "section": "Refactoring"},
        {"type": "test", "section": "Testing"},
        {"type": "docs", "section": "Documentation"},
        {"type": "chore", "hidden": true},
        {"type": "style", "hidden": true}
    ]
}
```

But the CLI does not respect the settings.

```
conventional-changelog -p conventionalcommits -r 0 --config tmp.json
```

**Comment by trallnag** [comment]
> What do you really mean select which type? and all options are already written in the docs.

I'm pretty sure that he means the mapping of commit types like `feat` and `fix` to sections like `Features` and `Bug Fixes`. The options themselves are documented, but the problem is to make conventional-changelog understand the configuration

**Comment by trallnag** [comment]
Place a `config.json` with content similar to this here:

```json
{
  "options": {
    "preset": {
      "name": "conventionalcommits",
      "types": "add list of json objects here"
    }
  }
}
```

Ensure that `conventional-changelog-cli` is installed. Execute the following:

```shell
conventional-changelog -r 0 --config config.json
```
