### ISSUE TITLE
Where did the specification links go?

### ISSUE THREAD

**Issue by alexbooker** [ajoslin/conventional-changelog#139]
Prior to 48580b039197f45574f309b1c2ade18c17c2933b there was a folder called [`conventions`](https://github.com/ajoslin/conventional-changelog/tree/81860ab6529d45422a78251951b458289df9405c/conventions). 

Is there a recommended place to find this information now?

**Comment by stevemao** [comment]
It's in their own repo now.. EG: https://github.com/stevemao/conventional-changelog-angular/blob/master/convention.md

**Comment by alexbooker** [comment]
@stephanebachelier Thanks!
