### ISSUE TITLE
Subgrouping by scope 

### ISSUE THREAD

**Issue by karol-f** [ajoslin/conventional-changelog#140]
In older version of conventional changelog (0.0.17), changelog was automatically grouped not only by "Bug Fixes"/"Features" but also subgrouped by "scope". Like in example below (using angular commit convention):

![grouping](https://www.dropbox.com/s/qb7vc7kny161nau/changelog_grouping.png?dl=1)

As we can see "cart" scope become group for all commits from that scope. Is this possible to have same functionality in current version of conventional-changelog? If no, how to achieve it?

**Comment by stevemao** [comment]
Have you tried tweaking the templates?

**Comment by stevemao** [comment]
You might need to tweak a few other options as well. I think you should be able to achieve it. Let me know how it goes.

**Comment by karol-f** [comment]
@stevemao I don't know where to start as template tweaking requires "scope" subgroups to be actually created. Probably in "transform" of writer. In conventional-changelog 0.0.17, where angular preset was built in, there was ForEach that detect if subgroup is needed. I can't see it in code of angular-preset.

**Comment by stevemao** [comment]
`forEach` is done by handlebarsjs. You just need to tweak other options (probably `writerOpts.transform`)

**Comment by karol-f** [comment]
Ok, I'll try to just use transform and write my own. Thanks

**Comment by stevemao** [comment]
I don't remember if it was grouped like that to be honest. I tried to achieve similar results for the angular preset.

**Comment by LanNobul** [comment]
You can use finalizeContext to subgroup the changelog. Because the handlebar can only group it once, if you want to sub-group you data, just define your own, and use the handlebar to render it.
```
const finalizeContext = (context, options, commits) => {
// group your data here
return context;
};
```
```
const writerOpts = {
  finalizeContext: finalizeContext
};
```
```
conventionalChangelogCore(
  (options = {}),
  (context = {}),
  (gitRawCommitsOpts = {}),
  (parserOpts = {}),
  writerOpts
).pipe(process.stdout);
```
