### ISSUE TITLE
can't get it to work

### ISSUE THREAD

**Issue by simon-at-angelsdice** [ajoslin/conventional-changelog#142]
Hi,
I'm sure I'm missing something really obvious with this, but when ever i use the the gulp-conventional-changelog using the following code:

`gulp.task('changelog', function () {`
`  return gulp.src('CHANGELOG.md', {`
`    buffer: false`
`  })`
 `   .pipe(conventionalChangelog({`
 `     preset: 'angular' // Or to any other commit message convention you use.`
 `   }))`
 `   .pipe(gulp.dest('./'));`
`});`

i get the following error:

`/node_modules/gulp-conventional-changelog/node_modules/conventional-changelog/node_modules/conventional-changelog-core/node_modules/git-remote-origin-url/index.js:2`

`const gitconfig = require('gitconfiglocal');`

Any help would be greatly appreciated.

**Comment by stevemao** [comment]
some common things you need to write when you report an issue:
1. versions
2. project setup
3. full call stacks
3. any useful information

**Comment by stevemao** [comment]
@simon-at-angelsdice why closing this?

**Comment by simon-at-angelsdice** [comment]
I'm closing as it is now working!

Really not sure what was wrong. It wouldn't work on my ubuntu box at all. I opened the project on my mac and was all working fine. Made some unrelated code fixes. Switched machines again and then it all worked?!

I did notice that you seem to be getting the same error in this travis job:

https://travis-ci.org/ajoslin/conventional-changelog/jobs/109305271 <https://travis-ci.org/ajoslin/conventional-changelog/jobs/109305271>

**Comment by stevemao** [comment]
They both passed tests. What do you mean error?

**Comment by simon-at-angelsdice** [comment]
Yes they are passing, however if you look at lines 323 - 325 you will see the same issue that i was getting

**Comment by stevemao** [comment]
The warnings are fine. It means your using old nodejs and a minor feature that's not supported.

**Comment by stevemao** [comment]
It shouldn't stop you running the program.

**Comment by simon-at-angelsdice** [comment]
That's good then. Glad its not an issue.

I really have no idea why when i was getting this issue it wasn't generating a changelog.md. Anyway i now have it working and its performing exactly as i had hoped, so thank you for creating it :)
