### ISSUE TITLE
Colons (:) are not allowed in scope name

### ISSUE THREAD

**Issue by boroth** [ajoslin/conventional-changelog#21]
I'd like to update the regex that's used in parseRawCommit() in git.js. 

I have a few commits that aren't being added to changelog that aren't being detected because they're formatted as such: 

`fix(category:subcategory): My subject`

I've updated locally for myself, here's the regex that I've added:

`var COMMIT_PATTERN = /^(\w*)(\(([\w\:\$\.\-\*]*)\))?\: (.*)$/;`

**Comment by stevemao** [comment]
Can you send a pull request with tests associated? Thanks

**Comment by stevemao** [comment]
Closing for #13
