### ISSUE TITLE
Why it returns the whole change log

### ISSUE THREAD

**Issue by eskimoblood** [ajoslin/conventional-changelog#24]
Whats the reason for not writing the change log into a the file but returning it as a string. I expected that it would write into the file in the first place. After thinking about it I can see reasons for just returning the string but then I would expect that it would only return the last changes not the whole change log, cause this can be done by the user if needed.

**Comment by stevemao** [comment]
It will return a stream in the future.

It should only generate the logs from latest tag only. Closing this for now. if you find out its this modules's issue please post a reply with more details (how to replicate etc) and we can reopen. Thanks.

**Comment by stevemao** [comment]
Correct my mistake.

from {string} - Which commit the changelog should start at. By default, uses previous tag, or if no previous tag the first commit.

to {string} - Which commit the changelog should end at. By default, uses HEAD.

If there is a problem please reply with details.
