### ISSUE TITLE
Option to only include breaking changes in the changelog

### ISSUE THREAD

**Issue by gpleiss** [ajoslin/conventional-changelog#28]
When we create a release on our project, we want to include all the changes (bug fixes, features, breaking changes) in the github release notes. However, in our changelog we only want to include the breaking changes.

It would be nice if there was a option that we could pass in to configure this. I.e.

```js
changelog({
  ...
  changeLevels: ['features', 'breaking']
}, function(err, log) {
  ...
});
```

This would only include new features and breaking changes. If the argument isn't supplied, it defaults to all types.

Would you be open to a PR?

@gpleiss, @bebepeng @stubbornella, @drpep

**Comment by stevemao** [comment]
Closing for #12
