### ISSUE TITLE
shortcut repository url format

### ISSUE THREAD

**Issue by marcin-wosinek** [ajoslin/conventional-changelog#37]
npm allows users to specify repository as 'npm/npm' - when there is no htttp:// nor git:// in url it assumes github. The address is created by [github-url-from-username-repo](https://www.npmjs.com/package/github-url-from-username-repo). Currently this format is not understood properly by conventional-changelog. This format is not very pupular but at least in generator-angular it caused [issues](https://github.com/yeoman/generator-angular/pull/998).

I will try to prepare PR in the free time.

**Comment by marcin-wosinek** [comment]
looks that it was grunt-conventional-changelog was parsing package.json in my setup.

**Comment by stevemao** [comment]
landed in https://github.com/ajoslin/conventional-changelog/commit/cb1feb7dd8f14cc55472fd0fbc229f23782c7582

**Comment by stevemao** [comment]
I added more tests because I'm very paranoid. Please let us know if you find any problem. Thanks
