### ISSUE TITLE
deprecate options.file

### ISSUE THREAD

**Issue by stevemao** [ajoslin/conventional-changelog#40]
Since this module will return a stream, we should let wrapper modules to deal with how they want to handle logs (prepend or append texts etc...) and let this module focus on generating logs.

eg in bash we could do

```sh
changelog --from 277ebe3a68fd1e72cf7ed15c2b605b847dd3c683 >> CHANGELOG.md
```

**Comment by stevemao** [comment]
After I did more research, its probably better to keep the main functions like this but add a stream interface.

**Comment by ajoslin** [comment]
I'm fine with `options.file`, but I think we should get rid of the default.

High potential for confusion: someone is using `changelog` CLI, and they have an existing CHANGELOG.md. We default options.file to their file, and we mutate their changelog.md without them knowing.

**Comment by stevemao** [comment]
Good idea, by default it should print to `stdout` unless a file is specified.

**Comment by stevemao** [comment]
I think it shouldn't write to a file in this module. grunt and gulp have file handling. wrappers of this module should handle this.

**Comment by stevemao** [comment]
CLI, however, should handle this but not in the core.

**Comment by stevemao** [comment]
Reasons that this core module shouldn't handle the file:
1. The old log is just to be appended or prepended to the newly generated log, which is a very simple thing that could be done in the parent module.
2. We want it to be very flexible for the parent module.
You might create a readable stream from the file or you might just read the file.
3. We want the duty of this module to be very minimum.

We might separate the cli once the module expands.
