### ISSUE TITLE
Setting option defaults

### ISSUE THREAD

**Issue by ajoslin** [ajoslin/conventional-changelog#41]
We should make our option defaults all be set in index.js, if possible. It's getting too scattered and confusing (all the files except Writer.js change the options)

**Comment by stevemao** [comment]
I was just thinking about this actually. I think eventually it will become several smaller modules #22

So for each small modules they will have their defaults set. For this module, as a wrapper, will also have defaults set.

**Comment by ajoslin** [comment]
:+1: best case scenario accomplished

**Comment by ajoslin** [comment]
:+1: best case scenario accomplished

I love the work you're doing btw Steve.  All good stuff. you've actually inspired me to finally pull down the latest and fix a few things that have been bugging me!

**Comment by stevemao** [comment]
Thanks @ajoslin :smile:

**Comment by stevemao** [comment]
Please checkout the rewrite on the master branch and see if the problem still exists. Thanks.
