### ISSUE TITLE
Need an elegant way to fake the results of cp.exec() in lib/git.js

### ISSUE THREAD

**Issue by stevemao** [ajoslin/conventional-changelog#42]
This is for testing.

I could do something like 
```
if (process.env.test)
...
```

But I wonder if we can swap the actual 'child_process' package with my dodge package when testing.

**Comment by ajoslin** [comment]
https://github.com/jhnns/rewire

**Comment by stevemao** [comment]
Thank you :smile: , tried to search "fake require" but found none.
