### ISSUE TITLE
Request for release

### ISSUE THREAD

**Issue by rainboxx** [ajoslin/conventional-changelog#43]
Hey, I'd like to request a release because of 69cfb5c. The newest release is now 9 months old and some other fixes appeared in the master branch, too, so it could be a good time :).

Thanks!

**Comment by ajoslin** [comment]
@stevemao I think now's a good time, before we go crazy splitting everything apart. But I'll let you call it.

**Comment by stevemao** [comment]
Sounds good, I will do some tiny changes before we release. Thanks

**Comment by stevemao** [comment]
@ajoslin I just made some changes and I think it's ok to release. More tests/features will come once we split. Thanks.

**Comment by rainboxx** [comment]
Thanks!

Just out of curiosity, where can I find the plans or roadmap for the split?

**Comment by stevemao** [comment]
#22

**Comment by stevemao** [comment]
Ping @ajoslin

**Comment by ajoslin** [comment]
I'll  publish this  today.

**Comment by ajoslin** [comment]
ac24c39593b15a46ac6b34641797e6ffb883f262

I made the commit 10 days ago, but only just actually pushed the publish up.

**Comment by ajoslin** [comment]
...And because of that, I had to manually add one more fix. Woops.

https://github.com/ajoslin/conventional-changelog/commit/f2b0edab389ad53e42356b96cbc4e30d03d7ffe9

**Comment by ajoslin** [comment]
@stevemao what's your NPM username? I'll add you as an owner.

**Comment by ajoslin** [comment]
I messed up the release and had to force-push over it with v0.0.13. https://github.com/ajoslin/conventional-changelog/commit/43a03c76a12951ce5ef7a813b72c416fb2df7713

We desperately need a script for future releases, I keep messing them up.

**Comment by stevemao** [comment]
Thanks @ajoslin , my npm username is `stevemao`.

I think a release script is a good idea! This would be also useful for people not using grunt or gulp.

**Comment by ajoslin** [comment]
Added you.

**Comment by ajoslin** [comment]
And yes, `release.sh` would only be a few lines but it would be a huge help.

**Comment by stevemao** [comment]
Thank you @ajoslin :smile:
