### ISSUE TITLE
Should be able to easily generate changelog for any previous version(s).

### ISSUE THREAD

**Issue by stevemao** [ajoslin/conventional-changelog#45]

**Comment by dragn** [comment]
+1
The implementation could traverse tags one-by-one and gather changes between them, also making note of the date the version was released (tagged commit date).

**Comment by stevemao** [comment]
Oh that's a good point

**Comment by stevemao** [comment]
http://stackoverflow.com/a/6900369/3304774

Looks like Lightweight Tags do not store date information. So if using a lightweight tag the date would have to be the date of the commit that is tagged on :(.

**Comment by stevemao** [comment]
Also if multiple tags are found, it should probably use the highest semver (filter out the ones that are not semver first).

**Comment by stevemao** [comment]
Please checkout the rewrite on the master branch and see if the problem still exists. Thanks.
