### ISSUE TITLE
Problems with version 0.0.14

### ISSUE THREAD

**Issue by felixzapata** [ajoslin/conventional-changelog#47]
Hi, I think there is an issue with the last version on this task. If you have a project without tags and some commits, when you try to execute the task, the console shows  "Generating changelog from undefined to undefined". 

However, if you have a tag or you use the versión 0.0.11 the task works.  Maybe the problem is related with the `else` in the `getFirstCommit` function, because if the repository has commits executes this line:  `done(null, '');` (with the second parameter empty).

The versión 0.0.11 uses this line instead:

`done(null, String(stdout).split('\n')[0].split(' ')[0].trim());`

Regards.

**Comment by felixzapata** [comment]
hi, the problem persists. Now the message does not show "undefined" (this was a minor issue). The main problem is if you have no tags in your project, the task does not create the changelog file.

**Comment by stevemao** [comment]
Hi @felixzapata , thank you for reporting this. I'm trying to focusing on the next version so didn't spend too much time on the current codebase. Can you try #48 to see if it solves your problem?

**Comment by felixzapata** [comment]
Hi, sorry it does not work. The only fix I think it works is if you change the `done` function:

`done(null, String(stdout).split('\n')[0].split(' ')[0].trim());`

I can wait using the version 0.11.0 until you have the new version.

Regards

**Comment by stevemao** [comment]
That's weird cos I can generate cmd `git log --grep="^feat|^fix|BREAKING" -E --format=%H%n%s%n%b%n==END==` and this should get you all commits from the first one. Do you mind if you provide part of your log history (first 5 maybe)?

**Comment by stevemao** [comment]
Also can you console.log your git log cmd after https://github.com/ajoslin/conventional-changelog/blob/master/lib/git.js#L108? thanks

**Comment by felixzapata** [comment]
Hi, I will test later again but in this case with a fake repository with some commits and without tags with the code of your pull request for the git.js file. 

Maybe before, I've done incorrect the test with the code.

**Comment by felixzapata** [comment]
hi, I´ve tested with another repository without tags and with some commits. The results:
* the task from version 0.0.11 it works.
* the task from version 0.0.15 does not work.
* the task from version 0.0.15 with the code from pull-request #48 it works. 

Regards.

**Comment by felixzapata** [comment]
And by the way.. this is only for curiosity, the name `git.js` throws me a lot  of Window Script Host modal errors when I open this file and I try to save (only a single text line) in Sublime Text in Windows 7 (Sometimes I use Windows, other times Ubuntu). 

If you use another file name, the error does not appear.

**Comment by stevemao** [comment]
I don't know. But we will make big changes in the next release (see [roadmap](https://github.com/ajoslin/conventional-changelog#roadmap))

Thanks for testing this.
