### ISSUE TITLE
Link in CONVENTIONS.md is broken.

### ISSUE THREAD

**Issue by bachp** [ajoslin/conventional-changelog#56]
There is a link at the end of the [CONVENTIONS.md](https://github.com/ajoslin/conventional-changelog/blob/master/CONVENTIONS.md) that links to a document that doesn't exist.

> A detailed explanation can be found in this [document](https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y/).

**Comment by stevemao** [comment]
Just tried. It seems to work.

**Comment by bachp** [comment]
Ok it's working again too. Sorry fro the wrong alert ;)
