### ISSUE TITLE
Conventions dissapeared

### ISSUE THREAD

**Issue by iamstarkov** [ajoslin/conventional-changelog#61]
I have been stressed to see 404, when I was opening conventions cheat sheet to choose commit type for commit. Where I can find them now?

404 link is https://github.com/ajoslin/conventional-changelog/blob/master/CONVENTIONS.md#type

**Comment by iamstarkov** [comment]
nevermind, it is here now https://github.com/ajoslin/conventional-changelog/blob/master/conventions/angular.md =)

**Comment by stevemao** [comment]
Where do you get the link? Why does it link to a master branch where things might change?

**Comment by iamstarkov** [comment]
I get this link from searching inside repo.

> Why does it link to a master branch where things might change?

so what? I’m bookmarking it to my browser’s toolbar like this:
![screen shot 2015-06-12 at 01 27 37](https://cloud.githubusercontent.com/assets/559321/8120676/3f2348de-10a2-11e5-9cc0-3a38f49005c4.png)

**Comment by stevemao** [comment]
No worries. I thought it was referenced from a web page so that we need to fix.

**Comment by iamstarkov** [comment]
no, it’s only mine shortcut reference for types in conventional changelog
