### ISSUE TITLE
Allow to configure the headerPattern

### ISSUE THREAD

**Issue by mfilotto** [ajoslin/conventional-changelog#63]
Hi,
First of all, thanks for this great tool :+1: 
I would like to be able to configure the regexp headerPattern a bit to allow these variations:
```
<type>(<scope>): <subject>
```
```
 <type>(<scope>) : <subject>
```
```
 <type>(<scope>) <subject>
```
Thanks

**Comment by stevemao** [comment]
Can you try the master branch? I've published an alpha version to npm and you can install by the tag 'next' it should be already possible to do this and even more. Thanks.

**Comment by mfilotto** [comment]
As it's a one shot operation for my commit history, I found my way out with a temporary local monkey patch of your code v0.17.0
Thanks for your help
