### ISSUE TITLE
angular commit types not being expanded

### ISSUE THREAD

**Issue by richardthombs** [ajoslin/conventional-changelog#70]
Hi there,

Trying to get alpha 3 to work and at the moment although I can get a bare changelog produced, a commit message like:
```
feat(blah): my message
```
Comes out as

```
### feat

* feat(blah): my message
```

Looking at the docs and the tests, I was expecting:

```
### New features

* blah: My message
```

**Comment by stevemao** [comment]
Did you use the angular preset?

**Comment by richardthombs** [comment]
Doh, thank you :)
