### ISSUE TITLE
Add an option to respect the tags while using "allBlocks"

### ISSUE THREAD

**Issue by wzr1337** [ajoslin/conventional-changelog#71]
When I generate using "allBlocks" option, I get a changelog that holds everyting from the `from` to HEAD and uses just the latest version information from the `package.json` as the header for everything it found the logs.

I need to rebuild my log on every build, so I would like to have all the GIT-tags I set taken into account when generating the log.

My options:

```
{
    // Task-specific options go here.
    from : '1.0.0',
    allBlocks: true
}
```

**Comment by stevemao** [comment]
are you using the latest alpha version? `from` option should go into git-raw-commits and `allBlocks` should go to conventional-changelog-writer.

**Comment by stevemao** [comment]
I think you want to generate all blocks from a committish? If so, you need to manually set `from` option for `git-raw-commits` and `allBlocks` for this module. Closing now. If you have problem please reply to this thread and we can reopen. Thanks.
