### ISSUE TITLE
Generating a changelog when there's a git tag present

### ISSUE THREAD

**Issue by aaronwest** [ajoslin/conventional-changelog#73]
I've been working with conventional-changelog over the past two days and ran into some behavior that seemed odd. I'm not sure if it's an issue or not but since the version I'm using is the latest beta I thought I'd report it in case it is an issue or in case I'm doing something wrong.

I'm using *conventional-changelog@^0.1.0-beta.3* on Mac OS X 10.10.4 with Node.js v0.12.4. I'm able to generate CHANGELOG.md using the following code but only under certain conditions.

```
conventional-changelog -o CHANGELOG.md -p angular -v
```

**Scenario 1:**
If I have conventional-changelog installed as a global npm module the code works. If it's installed as a local npm module I get the following error:
```
-bash: conventional-changelog: command not found
```
This could be an issue with something I'm doing. Or not doing.

**Scenario 2:**
If I have created a tag with *git tag -a v0.0.1 -m "Initial testing release."* the code above doesn't work. A changelog file is created but it's blank/empty. If I delete the git tag and rerun conventional-changelog, a changelog is generated and has content as expected.

Thanks for the work on this tool. Our engineering team is looking at using it to help us with better process and better documentation right from our commit logs.

**Comment by stevemao** [comment]
Scenario 1: this is not related to this module. You need to install globally to use the cli
Scenario 2: this commit does not comply to the angular commit convention. If you are not using angular commit convention don't specify a preset.

**Comment by aaronwest** [comment]
@stevemao thanks for the response. With scenario 2 usage of a specific convention doesn't appear to play a role in what I'm seeing. If I don't have a *git tag* present I can generate a changelog using whichever convention I want and the resulting CHANGELOG.md is created according to the convention. But if at least one tag is present an empty CHANGELOG.md is always created.

Here's some examples:
```
git tag -a v0.0.1 -m "Initial testing release."
conventional-changelog -o CHANGELOG.md -v
# CHANGELOG.md is created and is completely blank
```

```
git tag -a v0.0.1 -m "Initial testing release."
conventional-changelog -o CHANGELOG.md -p angular -v
# CHANGELOG.md is created and is completely blank
```

```
git tag -d v0.0.1
conventional-changelog -o CHANGELOG.md -v
# CHANGELOG.md is created as expected with no commit convention
```

```
git tag -d v0.0.1
conventional-changelog -o CHANGELOG.md -p angular -v
# CHANGELOG.md is created as expected with the angular commit convention
```

What seems odd about all these examples is how the presence of a tag yields a blank CHANGELOG.md. Is this normal or is there a different way to run conventional-changelog when tags exist?

**Comment by stevemao** [comment]
You can specify a `from` options for git-raw-commits. It defaults to the latest semver tag. You can also regenerate all blocks from the first commit with option `allBlocks`. Does it help?

**Comment by stevemao** [comment]
I'm going to close this issue as git-raw-commits can emit a close event even if there is no commits. Also be aware that the default `from` is the latest-semver-tag, reason being the recommended workflow of not using `allBlocks` is 

- Make changes
- Commit those changes
- Bump version in package.json
- conventionalChangelog
- Commit
- Tag

you can change `from` manually or just use `allBlocks`.

**Comment by aaronwest** [comment]
@stevemao thanks for posting the recommended workflow. That was super helpful. The issue was me not understanding the proper sequence of events when committing various changes, generating the CHANGELOG and tagging. After playing around with a testing repo I've got it all sorted.
