### ISSUE TITLE
Version not parsed from package.json if "repository" field not set in file.

### ISSUE THREAD

**Issue by klamping** [ajoslin/conventional-changelog#74]
The issue occurs on [line 88 of index.js](https://github.com/ajoslin/conventional-changelog/blob/master/index.js#L88). `getPkgRepo` fails if there is no `repository` information, which prevents the version information from being added to the `context` object, causing blank values in the changelog output. 

I'll see if I can get a PR out for this.

Steps to recreate:
1. Have an NPM repository without a `repository` field:
```
{
  "name": "my-package",
  "version": "1.0.1",
}
```
2. Run `conventional-changelog`
3. See that output does not pick up `version` information

**Comment by stevemao** [comment]
Released as 0.1.2
