### ISSUE TITLE
Items are added twice to the changelog

### ISSUE THREAD

**Issue by Dignifiedquire** [ajoslin/conventional-changelog#81]
Running `grunt release` on karma, produced this Changelog: https://github.com/karma-runner/karma/blob/master/CHANGELOG.md#0137-2015-08-05 which includes the two items from the previous release. Any ideas what's going on?

**Comment by Dignifiedquire** [comment]
I forgot to pull the latest tags before, sorry for creating noise.

**Comment by stevemao** [comment]
its ok :) I feel like its pretty hard to use as you have to strictly follow the steps.
but i can't really do much about it :(
