### ISSUE TITLE
Filter out issues

### ISSUE THREAD

**Issue by pjpsoares** [ajoslin/conventional-changelog#89]
What do you think if we had a filter option that would allow to filter out commits? This could be quite useful if you have a lot of commits for the same issue, and you only want one message on the changelog.

**Comment by stevemao** [comment]
Hey there I can think of three options:
1. Use `--grep` option on `git-log`. git-raw-commits is a wrapper of `git-log` so you can pretty much pass in any options. But there might be a key commit that triggers to generate a release being filtered.
2. Use `writerOpts.transform` if it returns false the commit is ignored.
3. Reverted commits are ignored by default. If you want to ignore a commit you could revert it. You can customise revert patterns using `parserOpts.revertPattern` and `parserOpts.revertCorrespondence`.
Are these more or less you are looking for?

**Comment by pjpsoares** [comment]
I tried the transform function returning false and it worked fine. It seemed the less hacky solution so I went with it. Nice! Thank you.

**Comment by pjpsoares** [comment]
Another question, if I need to call some http endpoint on the transform function. Do you have any suggestion on how can I do that? It would probably be cool if the transform function could also return a promise.

**Comment by stevemao** [comment]
`transform` is called on every commit. So you wouldn't want to make a http request for every commit. I think you need to call the http endpoint first then run this module.

**Comment by pjpsoares** [comment]
Imagine I have the gitlab issue on the commit message. I want to call the gitlab api for each issue I found so that I can put the gitlab title on the changelog instead of the commit message. I could push all issues from gitlab but I don't see that as a better approach as most times your changelog will have 2 or 3 issues, and in the long run you could have a lot of issues.

**Comment by stevemao** [comment]
I think pulling all is better as http requests are slow and you need to avoid it as much as possible. Can you do this within one http request?

**Comment by stevemao** [comment]
Oh I see what you mean. So can you pull all issues of the current release within a request?

**Comment by pjpsoares** [comment]
I can pull all issues, not sure about how you would filter. But probably it won't be much of an issue, since it's an internal call.

**Comment by stevemao** [comment]
I think this is quite interesting, I never thought we should make transform async. Not sure if there are valid use cases. If we do have an option, I'm towards a `callback` solution instead of promise.

**Comment by pjpsoares** [comment]
The advantage of being a promise is that you can easily support both based on the type of the response. Not as easy with callback.

**Comment by stevemao** [comment]
I think in your case you don't need async transform because if you have 100 commits and you might need to make 100 requests (as you said you could get everything by one request which is much better). A valid use case would be you need to know about the commit, do some async operation, then transform the commit. I'm not sure if this use case exists but it will definitely slow down the whole thing.

**Comment by pjpsoares** [comment]
In my particular case we are going to need it. Because our commits can either come from gitlab or from rally. And to fetch them from rally we would need the specific id. I already made an implementation for this. It's just adding a couple of lines on conventionalChangelogWriter. I'm going to make a merge request with the changes later today, and you can see if you like it.

**Comment by stevemao** [comment]
Moving discussion to https://github.com/stevemao/conventional-changelog-writer/pull/11
