### ISSUE TITLE
document available parameters

### ISSUE THREAD

**Issue by oupala** [ajoslin/conventional-changelog#90]
I can see in the README file some parameters to the command line :

```
-p angular
-i CHANGELOG.md
-w
-r 0
```

Where are these parameters documented ?

**Comment by stevemao** [comment]
Here https://github.com/ajoslin/conventional-changelog#cli
```
$ conventional-changelog --help # for more details
```
Because all the details are included when you run the command. If you have a better idea of how to document it better please send a PR.

**Comment by oupala** [comment]
PR #92 available.
