### ISSUE TITLE
angular: `scope` is missing from breaking changes

### ISSUE THREAD

**Issue by bekos** [ajoslin/conventional-changelog#93]
On angular preset, the generated breaking changes don't reference the scope for each change.
This should be the default behaviour IMO. Thx.

**Comment by stevemao** [comment]
I don't understand. Can you elaborate?

**Comment by bekos** [comment]
Sure. You can see [here](https://github.com/angular/angular.js/blob/master/CHANGELOG.md#breaking-changes) what I mean.

If a commit message is like:
```js
fix(ngAnimate): ....

Breaking chnage: due to .....
```

I expect on `Breaking Changes` section, the `ngAnimate` to be referenced, like:
```js
* ngAnimate: due to ...
```
and not just
```js
* due to ...
```
like it is happening now.

**Comment by stevemao** [comment]
This is defined by the angular project. Only if your "type" is `feat`, `fix` or `perf` it will appear in the changelog. If you think this is not correct, you should probably open an issue there.
Or use the angular preset and change the settings to your needs.

**Comment by bekos** [comment]
I referring **only** to the `Breaking Changes` section, not the `Bug fixes` or the `Features`. On the `Breaking changes` section, for each breaking change there is not reference to the `<scope>` of the commit.

**Comment by pkozlowski-opensource** [comment]
@bekos are you saying that breaking changes should be added regardless of the type of change, that is - also for refactor in this case?

I would argue that other types of changes (refactor, docs, tests) shouldn't actually contain breaking changes. Otherwise it is more than just a refectoring.... Just my $0.03....

**Comment by bekos** [comment]
@pkozlowski-opensource Nope.

I'm just telling that if the <scope> of the commit message, ie `ngAnimate is not referenced in the `Breaking changes` section. Just look at my example above :-)

**Comment by stevemao** [comment]
I see what you mean now. I don't think angular projects are doing this. You can easily modify the template to achieve this.

**Comment by bekos** [comment]
For Angular 1.x this is the way they used to do this and are still doing this. Angular 2.x is not, but I think this is a problem, because if you forget to explicitly repeat the `<scope>` of the commit, in the text of the breaking change, it can be very confusing.

I argue about the default usage, but if this is something I can easily override on my side, through the templates, Im fine with it :-)

**Comment by stevemao** [comment]
@pkozlowski-opensource is it the expected behaviour? The template for the presets can be changed.

**Comment by stevemao** [comment]
@bekos @pkozlowski-opensource I think it was modified so that they don't care about the `scope` in the `breaking changes` any more? Or we just forgot it in the default?

**Comment by bekos** [comment]
My opinion is that without `scope` you lose the context, and you cannot easily find out if the breaking change affects you.

**Comment by oupala** [comment]
`scope` of **breaking change** does not appear in the changelog, but it is not in bold as it should be.

Scopes are in bold in the changelog, except in the breaking change. I think this is a bug. Isn't it?

**Comment by stevemao** [comment]
Angular team didn't give me the requirement on this. So this whole issue wasn't a bug. I just thought it made sense to add them. I don't know what format it should be.

**Comment by oupala** [comment]
As you include the scope in the breaking change, I thought it would be more consistent that scope would always be in bold, in bugfixes, features and in breaking change. Don't you think ?

**Comment by stevemao** [comment]
@oupala PR welcome :) I don't know what the angular team whats so I don't have any thoughts.
