### ISSUE TITLE
fail to import context.json file

### ISSUE THREAD

**Issue by oupala** [ajoslin/conventional-changelog#96]
A recent commit (feceb8b2c86f3a2935d9f52143a8a838a51abe48) tries to import required file at the correct directory.

It does work when importing a file with a relative path (as the relative path is built from the current path).

But it does not work when using an absolute path.

I call conventional-changelog from `/home/user/dev/myproject/` and the json file is then at `/home/user/dev/myproject/context.json`.

Using the following command will work as context.json path will be built as `/home/user/dev/myproject/` + `context.json` (I guess)  which equals to `/home/user/dev/myproject/context.json`.

`changelog [...] -c context.json`

But the following command will **not** work as context.json path will be built as `/home/user/dev/myproject/` + `/home/user/dev/myproject/context.json` (I guess) which equals to `/home/user/dev/myproject/home/user/dev/myproject/context.json`.

`changelog [...] -c /home/user/dev/myproject/context.json`

**Comment by stevemao** [comment]
Fix welcome

**Comment by stevemao** [comment]
Please include tests to prove it actually works. I also forgot to add some tests for feceb8b2c86f3a2935d9f52143a8a838a51abe48

**Comment by oupala** [comment]
I won't be the one who writes the fix, I'm really not skilled enough for that. Sorry.
