### ISSUE TITLE
fail to generate valid linkReferences

### ISSUE THREAD

**Issue by oupala** [ajoslin/conventional-changelog#97]
The generated linkReference are invalid links:

```
* switch from GPLv2 to GPLv3 ([5759356](//commits/5759356))
```

It appears that some informations from the default package.json file are not imported.

My package.json is at root level of the projet, and I tried to call `convention-changelog` with or without the -k parameter (with relative and absolute path).

**Comment by stevemao** [comment]
Related to #91?

**Comment by stevemao** [comment]
@oupala 
Are you trying to generate the changelog in a sub directory of your project?

**Comment by oupala** [comment]
No, my package.json is at the root level of my project. And I'm trying to generate the changelog at the root level of my project to a file also located at the root level of my project. Everything is in the same directory: the root level of my project.

I was using a windows system so it could have been the cause of the problem. But I just tried to reproduce the problem on a linux box and I also have a failing behaviour.

I'm using conventional-changelog v0.4.2 and below is my package.json file:

```json
$ more package.json 
{
  "name": "project",
  "version": "3.1.0",
  "homepage": "https://git.example.org/group/project",
  "license": "GPL-3.0",
  "repository": {
    "type": "git",
    "url": "https://git.example.org/group/project.git"
  },
  "scripts": {
    "changelog": "conventional-changelog -p angular -c changelog.json -i partial-CHANGELOG.md -w -r 0"
  }
}
```

And when I run: `conventional-changelog -p angular -k package.json -o partial-changelog.md -r 0`, the generated logfile looks like:

```
<a name="3.1.0"></a>
# [3.1.0](//compare/3.0.0...v3.1.0) (2015-09-03)


### Bug Fixes

* restoring secure permissions 98d4f15

### Features

* replace old headers by GPLv3 headers e6567cf
* switch from GPLv2 to GPLv3 5759356
* **doc:** add CONTRIBUTE.md file 1087891
* **doc:** add a README file fc48241
```

**Comment by stevemao** [comment]
`https://git.example.org/group/project` is not a supported host and so `context.linkReferences` defaults to `false`
If you set `context.linkReferences` to `true` is should link.

**Comment by oupala** [comment]
Are github, bitbucket and gitlab the [only hosts supported](https://github.com/ajoslin/conventional-changelog/blob/831c960936e3d9d5d08eae46dd332c77dc8664dc/index.js#L15)?

**Comment by oupala** [comment]
By the way, there is a [typo](https://github.com/ajoslin/conventional-changelog/blob/831c960936e3d9d5d08eae46dd332c77dc8664dc/index.js#L18) in source file:

**conventinalChangelog** instead of **conventionalChangelog**

**Comment by stevemao** [comment]
See https://github.com/ajoslin/conventional-changelog/issues/80

**Comment by oupala** [comment]
Right, it's better now, with `"linkReferences": true` I get links generated.

But links are invalid:

```
* switch from GPLv2 to GPLv3 ([5759356](//commits/5759356))
```

I can see a way to specify a specific host that is not github, nor gitlab, nor bitbucket.

**Comment by oupala** [comment]
I'm using a private instance of GitLab.

Using conventional-changelog should be pretty straightforward...

**Comment by oupala** [comment]
Thanks to @rsids (from #98), I can manage to generate a decent CHANGELOG.

I used the following context file (to be used with a private gitlab instance):

```json
$ more changelog.json 
{
    "host": "https://git.example.org",
    "repository": "group/project",
    "commit": "commit"
}
```

This should be added somewhere in the documentation as it could really save time for common users.

**Comment by stevemao** [comment]
merge with #98
