### ISSUE TITLE
If get-pkg-repo fails to get info, it should fall back to the original repo url

### ISSUE THREAD

**Issue by rsids** [ajoslin/conventional-changelog#98]
The changelog only includes issues when the repository url is a known url (eg bitbucket or github). When using a private url, the generator doesn't parse the issuenumbers

**Comment by stevemao** [comment]
The intension was to use `get-pkg-repo` to get repo info and if it fails, it should fall back to the original repo url. I'll have to have a look.

**Comment by rsids** [comment]
When you use an unknown repo, you have to specify the host, repo & commit value in the context object. That will relink the commits, but it won't link the issues.
Even if it would, there should be an extra option for the issue links. In the project we're using conventional changelog, the repo has an entirely different url as the issuetracker.

**Comment by oupala** [comment]
@rsids Could give an example about how to specify host, repo & commit value in the context object.

Thanks.

**Comment by rsids** [comment]
```
context: {
      // context goes here
      host: 'https://git.HOST.nl/projects/ON/repos',
      repository: 'REPONAME',
      issue: 'issues',
      linkReferences: false
},
```
I've just found that it won't link the issues since I hadn't specified the referenceActions in the parserOpts. Which shouldn't be necessary, since I just want to use the defaults.
With the referenceActions specified, the issues are appended, but all prefixed with a #, not with the prefix I specified in issuePrefixes, see #99.
Furthermore, our git repo is at https://git.HOST.nl/..., while are issuetracker is as https://jira.HOST.nl/..., now, all the issues are linkt to git.HOST.nl.

**Comment by stevemao** [comment]
for host defaults, we only support three. PR welcome for more hosts #80

**Comment by stevemao** [comment]
Blocked by #91 which is blocked by https://github.com/sindresorhus/read-pkg/issues/2

**Comment by stevemao** [comment]
Also @rsids please keep this issue focused. I already opened #80 to track for more host support. Let's keep this for the fallback if repo cannot be parsed by `get-pkg-repo`

**Comment by destroyerofbuilds** [comment]
I'm encountering the same issue while working with a package hosted on an on-premise GitLab instance.

Here's the results of running `get-pkg-repo` directly:

```bash
get-pkg-repo package.json
{ protocol: 'https:',
  slashes: true,
  auth: null,
  host: 'gitlab.example.com',
  port: null,
  hostname: 'gitlab.example.com',
  hash: null,
  search: null,
  query: null,
  pathname: '/mygroup/mymodule.git',
  path: '/mygroup/mymodule.git',
  href: 'https://gitlab.example.com/mygroup/mymodule.git',
  browse: [Function] }
```

**Comment by raido** [comment]
I am having same issues with on premises repos. Futher more i would like to even link issues with tools like JIRA and others.

**Comment by stevemao** [comment]
@raido #80
