### ISSUE TITLE
Issue prefixes are replaced with #

### ISSUE THREAD

**Issue by rsids** [ajoslin/conventional-changelog#99]
When specifying multiple issue prefixes, all the issues in the changelog are prefixed with the same prefix (#). I'd expect that the prefix would be preserved.

**Comment by stevemao** [comment]
hm.. Currently only `reference.raw` exposes the prefix. We should add a field `referencePrefix`
```
expect(msg.references).to.eql([{
    action: 'handled',
    owner: 'angular',
    repository: 'angular.js',
    issue: '1',
    raw: 'angular/angular.js#1',

    // referencePrefix: '#'
}]);
```

**Comment by stevemao** [comment]
tracking at https://github.com/stevemao/conventional-commits-parser/issues/17
